# Note:
# Ansible doesn't allow to pass the password as clear test
# The password to be set has to be provided via a variable
# The is done when running the playbook.
# Run the playbook like this (newpassword is the variable in use):
# ansible-playbook change_password.yml --extra-vars newpassword=abc123
#
---
- name: Add or update user password
  hosts: all

  tasks:
          - name: Change "george" user's password
            user:
                    name: george
                    update_password: always
                    password: "{{ newpassword|password_hash('sha512') }}"
